# Generated by Django 5.0.6 on 2024-06-23 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloghome', '0003_alter_blog_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('comment', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('blogparent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloghome.blog')),
            ],
        ),
        migrations.CreateModel(
            name='reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('reply', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('commentparent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloghome.comment')),
            ],
        ),
    ]
